# Generated by Django 6.0.3 on 2026-04-12 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_api', '0003_alter_quotation_description_quotationitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='quotations/'),
        ),
    ]
