# Generated by Django 6.0.3 on 2026-04-12 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_api', '0004_quotation_pdf_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='floor_plan_2d',
            field=models.FileField(blank=True, null=True, upload_to='requirements/2d/'),
        ),
        migrations.AddField(
            model_name='lead',
            name='floor_plan_3d',
            field=models.FileField(blank=True, null=True, upload_to='requirements/3d/'),
        ),
    ]
