# Generated by Django 6.0.4 on 2026-04-13 08:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_api', '0005_lead_floor_plan_2d_lead_floor_plan_3d'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='prepared_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prepared_quotations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='QuotationSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('sort_order', models.PositiveIntegerField(default=1)),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='crm_api.quotation')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
