# Generated by Django 6.0.4 on 2026-04-13 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_api', '0007_meeting_assigned_user_meeting_client_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='reminder_sent',
        ),
        migrations.AddField(
            model_name='meeting',
            name='google_calendar_event_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.DeleteModel(
            name='UserDevice',
        ),
    ]
