# Generated by Django 6.0.4 on 2026-04-18 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_api', '0011_leadimport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('CONTACTED', 'Contacted'), ('MISSED_CALL', 'Missed Call'), ('MEETING', 'Meeting'), ('QUOTATION', 'Quotation'), ('DISCUSSION', 'Final Discussion'), ('CLOSED', 'Deal Closed'), ('LOST', 'Deal Lost')], default='NEW', max_length=20),
        ),
    ]
