# Generated by Django 6.0.4 on 2026-04-13 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='base_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='quotation',
            name='package_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='quotation',
            name='selected_package',
            field=models.CharField(choices=[('BASIC', 'LAMINATED (BASIC-ECO)'), ('SEMI', 'DUCO/VENEER/LAMINATE (Semi-Luxury Interior)'), ('FULL', 'PU-DUCO/VENEER/ACRYLIC/H.LAM (Full-Luxury Interior)')], default='BASIC', max_length=10),
        ),
    ]
