# Generated by Django 6.0.4 on 2026-04-13 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0002_quotation_base_amount_quotation_package_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='design_theme',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='quotation',
            name='exclusions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='execution_timeline',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='quotation',
            name='payment_terms',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='project_area_sqft',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='quotation',
            name='scope_of_work',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='warranty_terms',
            field=models.TextField(blank=True),
        ),
    ]
